# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLayout,
    QLineEdit, QMainWindow, QPushButton, QScrollArea,
    QSizePolicy, QSlider, QToolBox, QWidget)

from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(840, 400)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.settings = QScrollArea(self.centralwidget)
        self.settings.setObjectName(u"settings")
        self.settings.setGeometry(QRect(0, 20, 120, 380))
        self.settings.setFrameShape(QFrame.Shape.NoFrame)
        self.settings.setFrameShadow(QFrame.Shadow.Plain)
        self.settings.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.settings.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 120, 380))
        self.toolBox = QToolBox(self.scrollAreaWidgetContents)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setEnabled(True)
        self.toolBox.setGeometry(QRect(1, 0, 118, 379))
        self.toolBox.setFrameShape(QFrame.Shape.Box)
        self.sensorOptions = QWidget()
        self.sensorOptions.setObjectName(u"sensorOptions")
        self.sensorOptions.setGeometry(QRect(0, 0, 116, 287))
        self.labPortName = QLabel(self.sensorOptions)
        self.labPortName.setObjectName(u"labPortName")
        self.labPortName.setGeometry(QRect(1, -1, 113, 20))
        self.setPortName = QLineEdit(self.sensorOptions)
        self.setPortName.setObjectName(u"setPortName")
        self.setPortName.setEnabled(True)
        self.setPortName.setGeometry(QRect(1, 19, 113, 20))
        self.labMaxNewton = QLabel(self.sensorOptions)
        self.labMaxNewton.setObjectName(u"labMaxNewton")
        self.labMaxNewton.setGeometry(QRect(1, 119, 113, 20))
        self.setMaxNewton = QLineEdit(self.sensorOptions)
        self.setMaxNewton.setObjectName(u"setMaxNewton")
        self.setMaxNewton.setGeometry(QRect(1, 139, 113, 20))
        self.setGaugeValue = QLineEdit(self.sensorOptions)
        self.setGaugeValue.setObjectName(u"setGaugeValue")
        self.setGaugeValue.setGeometry(QRect(1, 59, 113, 20))
        self.labGaugeValue = QLabel(self.sensorOptions)
        self.labGaugeValue.setObjectName(u"labGaugeValue")
        self.labGaugeValue.setGeometry(QRect(1, 39, 113, 20))
        self.setNewtonPerCount = QLineEdit(self.sensorOptions)
        self.setNewtonPerCount.setObjectName(u"setNewtonPerCount")
        self.setNewtonPerCount.setGeometry(QRect(1, 99, 113, 20))
        self.setNewtonPerCount.setMaxLength(32767)
        self.labNewtonPerCount = QLabel(self.sensorOptions)
        self.labNewtonPerCount.setObjectName(u"labNewtonPerCount")
        self.labNewtonPerCount.setGeometry(QRect(1, 79, 113, 20))
        self.butConnect = QPushButton(self.sensorOptions)
        self.butConnect.setObjectName(u"butConnect")
        self.butConnect.setGeometry(QRect(1, 159, 113, 40))
        self.butConnect.setCheckable(True)
        self.butConnect.setChecked(False)
        self.butConnect.setFlat(False)
        self.toolBox.addItem(self.sensorOptions, u"Sensor")
        self.logOptions = QWidget()
        self.logOptions.setObjectName(u"logOptions")
        self.logOptions.setGeometry(QRect(0, 0, 116, 287))
        self.fileLabel = QLabel(self.logOptions)
        self.fileLabel.setObjectName(u"fileLabel")
        self.fileLabel.setGeometry(QRect(1, -1, 113, 20))
        self.butFile = QPushButton(self.logOptions)
        self.butFile.setObjectName(u"butFile")
        self.butFile.setGeometry(QRect(1, 19, 113, 22))
        self.butFile.setCheckable(True)
        self.toolBox.addItem(self.logOptions, u"Log")
        self.graphOptions = QWidget()
        self.graphOptions.setObjectName(u"graphOptions")
        self.graphOptions.setGeometry(QRect(0, 0, 116, 287))
        self.xLabel = QLineEdit(self.graphOptions)
        self.xLabel.setObjectName(u"xLabel")
        self.xLabel.setGeometry(QRect(1, 99, 113, 20))
        self.yLabel = QLineEdit(self.graphOptions)
        self.yLabel.setObjectName(u"yLabel")
        self.yLabel.setEnabled(True)
        self.yLabel.setGeometry(QRect(1, 59, 113, 20))
        self.yLabelLabel = QLabel(self.graphOptions)
        self.yLabelLabel.setObjectName(u"yLabelLabel")
        self.yLabelLabel.setGeometry(QRect(1, 39, 113, 20))
        self.xLabelLabel = QLabel(self.graphOptions)
        self.xLabelLabel.setObjectName(u"xLabelLabel")
        self.xLabelLabel.setGeometry(QRect(1, 79, 113, 20))
        self.xLimLabel = QLabel(self.graphOptions)
        self.xLimLabel.setObjectName(u"xLimLabel")
        self.xLimLabel.setGeometry(QRect(1, 119, 113, 20))
        self.title = QLineEdit(self.graphOptions)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(1, 19, 113, 20))
        self.titleLabel = QLabel(self.graphOptions)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(1, -1, 113, 20))
        self.xLimSlider = QSlider(self.graphOptions)
        self.xLimSlider.setObjectName(u"xLimSlider")
        self.xLimSlider.setGeometry(QRect(1, 139, 113, 20))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLimSlider.sizePolicy().hasHeightForWidth())
        self.xLimSlider.setSizePolicy(sizePolicy)
        self.xLimSlider.setMinimum(-1)
        self.xLimSlider.setMaximum(0)
        self.xLimSlider.setOrientation(Qt.Orientation.Horizontal)
        self.xLimSet = QLineEdit(self.graphOptions)
        self.xLimSet.setObjectName(u"xLimSet")
        self.xLimSet.setGeometry(QRect(1, 159, 113, 20))
        self.setPlotTimerInterval = QLineEdit(self.graphOptions)
        self.setPlotTimerInterval.setObjectName(u"setPlotTimerInterval")
        self.setPlotTimerInterval.setGeometry(QRect(1, 199, 113, 20))
        self.plotTimerIntervalLabel = QLabel(self.graphOptions)
        self.plotTimerIntervalLabel.setObjectName(u"plotTimerIntervalLabel")
        self.plotTimerIntervalLabel.setGeometry(QRect(1, 179, 113, 20))
        self.importGraphLabel = QLabel(self.graphOptions)
        self.importGraphLabel.setObjectName(u"importGraphLabel")
        self.importGraphLabel.setGeometry(QRect(1, 219, 113, 20))
        self.butFileGraphImport = QPushButton(self.graphOptions)
        self.butFileGraphImport.setObjectName(u"butFileGraphImport")
        self.butFileGraphImport.setGeometry(QRect(1, 239, 113, 22))
        self.butFileGraphImport.setCheckable(True)
        self.toolBox.addItem(self.graphOptions, u"Graph")
        self.settings.setWidget(self.scrollAreaWidgetContents)
        self.graph = QWidget(self.centralwidget)
        self.graph.setObjectName(u"graph")
        self.graph.setGeometry(QRect(120, 0, 600, 400))
        self.graph1 = PlotWidget(self.graph)
        self.graph1.setObjectName(u"graph1")
        self.graph1.setGeometry(QRect(0, 0, 600, 400))
        self.graph1.setFrameShape(QFrame.Shape.StyledPanel)
        self.graph1.setFrameShadow(QFrame.Shadow.Sunken)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(720, 20, 120, 380))
        self.butRecord = QPushButton(self.widget)
        self.butRecord.setObjectName(u"butRecord")
        self.butRecord.setEnabled(False)
        self.butRecord.setGeometry(QRect(1, 39, 115, 24))
        self.butRecord.setCheckable(True)
        self.butReGauge = QPushButton(self.widget)
        self.butReGauge.setObjectName(u"butReGauge")
        self.butReGauge.setEnabled(False)
        self.butReGauge.setGeometry(QRect(1, 129, 115, 24))
        self.butReGauge.setCheckable(True)
        self.timeLabel = QLabel(self.widget)
        self.timeLabel.setObjectName(u"timeLabel")
        self.timeLabel.setGeometry(QRect(1, -1, 115, 20))
        self.setTime = QLineEdit(self.widget)
        self.setTime.setObjectName(u"setTime")
        self.setTime.setGeometry(QRect(1, 19, 115, 20))
        self.butSave = QPushButton(self.widget)
        self.butSave.setObjectName(u"butSave")
        self.butSave.setEnabled(False)
        self.butSave.setGeometry(QRect(1, 87, 115, 24))
        self.butClear = QPushButton(self.widget)
        self.butClear.setObjectName(u"butClear")
        self.butClear.setGeometry(QRect(1, 63, 115, 24))
        self.butSingleRead = QPushButton(self.widget)
        self.butSingleRead.setObjectName(u"butSingleRead")
        self.butSingleRead.setEnabled(False)
        self.butSingleRead.setGeometry(QRect(1, 339, 115, 40))
        self.butSingleRead.setCheckable(True)
        self.timeLabel_2 = QLabel(self.widget)
        self.timeLabel_2.setObjectName(u"timeLabel_2")
        self.timeLabel_2.setGeometry(QRect(1, 319, 115, 20))
        self.settingsLabel = QLabel(self.centralwidget)
        self.settingsLabel.setObjectName(u"settingsLabel")
        self.settingsLabel.setGeometry(QRect(0, 0, 120, 20))
        self.buttonsLabel = QLabel(self.centralwidget)
        self.buttonsLabel.setObjectName(u"buttonsLabel")
        self.buttonsLabel.setGeometry(QRect(720, 0, 120, 20))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.toolBox.setCurrentIndex(0)
        self.butConnect.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Use the Force!", None))
        self.labPortName.setText(QCoreApplication.translate("MainWindow", u"Port Name", None))
        self.setPortName.setText(QCoreApplication.translate("MainWindow", u"COM3", None))
        self.labMaxNewton.setText(QCoreApplication.translate("MainWindow", u"Max Newton", None))
        self.setMaxNewton.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.setGaugeValue.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.labGaugeValue.setText(QCoreApplication.translate("MainWindow", u"Gauge Value", None))
        self.setNewtonPerCount.setText(QCoreApplication.translate("MainWindow", u"1.", None))
        self.labNewtonPerCount.setText(QCoreApplication.translate("MainWindow", u"Newton per Count", None))
        self.butConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.sensorOptions), QCoreApplication.translate("MainWindow", u"Sensor", None))
        self.fileLabel.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.butFile.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.logOptions), QCoreApplication.translate("MainWindow", u"Log", None))
        self.xLabel.setText(QCoreApplication.translate("MainWindow", u"Displacement [mm]", None))
        self.yLabel.setText(QCoreApplication.translate("MainWindow", u"Force [mN]", None))
        self.yLabelLabel.setText(QCoreApplication.translate("MainWindow", u"y-label", None))
        self.xLabelLabel.setText(QCoreApplication.translate("MainWindow", u"x-label", None))
        self.xLimLabel.setText(QCoreApplication.translate("MainWindow", u"x-scope", None))
        self.title.setText(QCoreApplication.translate("MainWindow", u"Force-Displacement Measurement", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"Title", None))
        self.xLimSet.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.setPlotTimerInterval.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.plotTimerIntervalLabel.setText(QCoreApplication.translate("MainWindow", u"Refresh Time (ms)", None))
        self.importGraphLabel.setText(QCoreApplication.translate("MainWindow", u"Import Graph Data", None))
        self.butFileGraphImport.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.graphOptions), QCoreApplication.translate("MainWindow", u"Graph", None))
        self.butRecord.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.butReGauge.setText(QCoreApplication.translate("MainWindow", u"ReGauge", None))
        self.timeLabel.setText(QCoreApplication.translate("MainWindow", u"Max Duration (s)", None))
        self.setTime.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.butSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.butClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.butSingleRead.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.timeLabel_2.setText(QCoreApplication.translate("MainWindow", u"Single read (mN)", None))
        self.settingsLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">Settings</span></p></body></html>", None))
        self.buttonsLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:700;\">Buttons</span></p></body></html>", None))
    # retranslateUi

